Fix error getting users profile.
DiscordAPIError: Interaction has already been acknowledged.
This would cause the server to restart.
https://stackoverflow.com/questions/71119936/discordapierror-interaction-has-already-been-acknowledged-discord-js-react-f